#Modules
import time
import commands

#Intro
print("Conquest for Exosite-5")
time.sleep(1)
print("Hello Player")
time.sleep(0.25)
print("In this digital world I am your eyes and hands")
time.sleep(1)
input("Is your character you a boy or a girl?")
time.sleep(0.5)
input("What is your character's name?")
player_name = input
time.sleep(.5)
print("hmm, what a wonderfull name.")
time.sleep(2)
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
print("SYSTEM FAILURE")
time.sleep(3)
print("Character Terminated")
time.sleep(1.5)
print("In this world there is no choices, only FATE.")
time.sleep(1)
print("Fate has made you a teenage boy by the name of...")
time.sleep(3)
print("GYREX")